### ISSUE TITLE
Tiles should not be cut off

### ISSUE THREAD

**Issue by kpyfan** [SharedMusic/SharedMusic#66]
If we want to leave them so they are cut off, we need to make them scrollable (which isn't a bad idea either).

**Comment by tcoval** [comment]
I want to make the tiles are click and draggable. What do you think about that option?

**Comment by tcoval** [comment]
Also I think having them not be cut off is a good idea, but I think it may be best to go with dynamically resizing tiles that are a percentage of the overall width.

**Comment by kpyfan** [comment]
Click->drag and/or scrolling the area is fine too. Do we have enough data to populate it?
